name: TypeScript - Lint, Build, Test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - 'typescript/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'typescript/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: typescript

jobs:
  main:
    timeout-minutes: 20
    name: Lint & Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "typescript/.nvmrc"
          cache: "yarn"
          cache-dependency-path: "typescript/yarn.lock"
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check Copyright Header
        run: yarn copyright:check
      - name: Code Lint
        run: yarn lint
      - name: Code Format
        run: yarn format
      - name: Commits Lint
        run: yarn commitlint --verbose --from "${{ github.event.pull_request.base.sha || github.event.commits[0].id || github.event.before || github.sha }}" --to "${{ github.event.pull_request.head.sha || github.event.head_commit.id || github.sha }}"
      - name: Documentation - code snippet embeddings
        run: yarn docs:check
      - name: Build
        run: yarn build
      - name: Unit Tests
        run: yarn test:unit
